name: souers Download
on: 
     workflow_dispatch:
permissions: write-all
jobs:
     clang-gcc-download:
       runs-on: ubuntu-24.04
       steps:
          - uses: actions/checkout@v3
          - name: Kernel Downloade
            run: |
                 sudo apt install repo git -y
         
                 mkdir $GITHUB_WORKSPACE/kernel_workspace/android-kernel 
                 cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
                 repo init --depth 1 -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10-2023-05
                 repo sync
                 cd ..
                 git clone https://github.com/lengxiaohua123/gki-lxc.git
                 cp ./gki-lxc/gki_defconfig ./android-kernel/common/arch/arm64/configs/gki_defconfig
                 cd android-kernel/common
                 git apply ../../gki-lxc/*.patch
                 cd ..
                 curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
                 cd .. 
                 tar -czvf archive.tar.gz android-kernel/*
          - name: Release
            id: create-release
            uses: softprops/action-gh-release@v1
            env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
               tag_name: 952701
               name: kernel Download
               body: TODO New Release.
               draft: false
               prerelease: false
               files: |
                 kernel_workspace/archive.tar.gz
                 
                 
