name: Clang Gcc Download
on: 
     workflow_dispatch:
permissions:
     contents: write
jobs:
     clang-gcc-download:
       runs-on: ubuntu-latest
       steps:
          - name: Download Clang-aosp
            run: |
                  mkdir $GITHUB_WORKSPACE/kernel_workspace
                  cd $GITHUB_WORKSPACE/kernel_workspace
                  mkdir clang-aosp
                  wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/main/clang-r510928/clang-r510928.tar.gz
                  wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz

           
