name: Clang Gcc Download
on: 
     workflow_dispatch:
permissions:
     contents: write
jobs:
     clang-gcc-download:
       runs-on: ubuntu-latest
       steps:
          - uses: actions/checkout@v3
          - name: Download Clang
            run: |
                  mkdir $GITHUB_WORKSPACE/kernel_workspace
                  cd $GITHUB_WORKSPACE/kernel_workspace
                  wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r510928.tar.gz
          - name: Download Gcc
            run: |
                  cd $GITHUB_WORKSPACE/kernel_workspace
                  mkdir clang-aosp
                  wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
          - name: Upload Clang
            uses: actions/upload-artifact@v3
            with:
              name: clang-r510928
              path: kernel_workspace/clang-r510928.tar.gz
          - name: Upload Gcc
            uses: actions/upload-artifact@v3
            with:
              name: gcc-android-12.1.0_r27
              path: kernel_workspace/android-12.1.0_r27.tar.gz

