name: Clang Gcc Download
on: 
     workflow_dispatch:
permissions: write-all
jobs:
     clang-gcc-download:
       runs-on: ubuntu-latest
       steps:
          - uses: actions/checkout@v3
          - name: Download Clang
            run: |
                  mkdir $GITHUB_WORKSPACE/kernel_workspace
                  cd $GITHUB_WORKSPACE/kernel_workspace
                  wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master-kernel-build-2022/clang-r450784d.tar.gz
          - name: Download Gcc
            run: |
                  cd $GITHUB_WORKSPACE/kernel_workspace
                  
          - name: Release
            id: create-release
            uses: softprops/action-gh-release@v1
            env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
               tag_name: 952700
               name: Clang Gcc Download
               body: TODO New Release.
               draft: false
               prerelease: false
               files: |
                 kernel_workspace/clang-r522817.tar.gz
                 
                 
